# Setup
title:        Dismistificando a Amazon Web Services
tagline:      Escolinha do Professor Samuka
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Samuel Sampaio (@samukasmk)
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
